config/routes.rb
Rails.application.routes.default_url_options[:host] = (Rails.env == 'production') ? 'bibliography.gr' : 'localhost:3000'
Rails.application.routes.draw do
  resources :shelves

  get '/autocomplete', to: 'home#autocomplete'

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :authors, :concerns => :paginatable do
    resources :awards, only: [:create, :edit, :update, :destroy]
    member do
      post 'favourite'
    end    
  end
  resources :awards, only: [:index], :concerns => :paginatable 

  resources :prizes, :contributions, :concerns => :paginatable

  resources :books, :concerns => :paginatable do
    member do
      get 'collections'
      post 'collections', to: 'books#manage_collections'
      post 'like'
      post 'dislike'
    end
    collection do
      get 'my'
    end
  end
  
  resources :publishers, :concerns => :paginatable do
    resources :places, only: [:create, :edit, :update, :destroy]
    collection do
      get 'search'
    end
  end 

  
  resource :profile, only: [:edit, :update]
  get "library/(:id)", :to => "profiles#show", as: 'public_profile'
  post "library/(:id)/follow", :to => "profiles#follow"

  
  
  get 'import', to: 'import#index', as: :import
  post 'import/url', to: 'import#import_from_url'
  post 'import/text', to: 'import#import_from_text'
  post 'import/file', to: 'import#import_from_file'

  get "import/storage", to: 'import#import_from_storage', as: :storage_import

  resources :categories do
    member do
      post 'favourite'
    end
  end

  devise_for :users

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
  

  namespace :api, defaults: {format: 'json'}  do
    namespace :v1 do
      resources :books, only: [:index, :show] do
        collection do
          get 'my'
        end
        resources :comments, except: [:new, :edit]
      end
      resources :authors, only: [:show] 
      resources :publishers, only: [:show]
      resources :categories, only: [:show]  
      resources :sessions, only: [:create]
      post 'authenticate', to: 'sessions#create'
    end
  end

  root to: 'home#index'

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :book
  belongs_to :author

  enum job: %i(συγγραφή μετάφραση ερμηνεία εικονογράφηση φωτογραφία επιμέλεια συνθέση στιχουργία εισήγηση διασκευή ανθολογία Φορέας Οργανισμός επιμέλεια\ σειράς επιμέλεια\ υποσειράς αφήγηση Ζωγράφος Γλύπτης Καλλιτέχνης κείμενα)

  default_scope { order('job') }
  scope :writers, -> { where(job: 0) }
  scope :contributors, -> { where.not(job: 0) }

  validates :book, presence: true
  validates :author, presence: true
  validates :job, presence: true

end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @contributions = policy_scope(Contribution).page(params[:page])
    authorize Contribution

    respond_with(@contributions)
  end

  def show
    respond_with(@contribution)
  end

  def new
    @jobs = Contribution.jobs
    @contribution = Contribution.new
    authorize @contribution

    respond_with(@contribution)
  end

  def edit
    @jobs = Contribution.jobs
  end

  def create
    @contribution = Contribution.new(contribution_params)
    authorize @contribution    
    @contribution.save

    respond_with(@contribution)
  end

  def update
    @contribution.update(contribution_params)

    respond_with(@contribution)
  end

  def destroy
    @contribution.destroy

    respond_with(@contribution)
  end

  private
    def set_contribution
      @contribution = Contribution.find(params[:id])

      authorize @contribution
    end

    def contribution_params
      params.require(:contribution).permit(:job, :book_id, :author_id)
    end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/_form.html.erb
<%= form_for(@contribution) do |f| %>
  <% if @contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

      <ul>
      <% @contribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-xs-12 form-group">
    <%= f.label :job %><br>
    <%= f.select :job, options_for_select(@jobs.collect { |s| [s[0].humanize, s[0]] }, selected: @contribution.job), {}, class: 'form-control' %>    
  </div>
  <div class="field col-xs-6 form-group">
    <%= f.label :book_id %><br>
    <%= f.text_field :book_id, class: 'form-control'  %>
  </div>
  <div class="field col-xs-6 form-group">
    <%= f.label :author_id %><br>
    <%= f.text_field :author_id, class: 'form-control'  %>
  </div>
  <div class="actions col-xs-6 form-group">
    <%= f.submit 'Save', class: 'form-control btn-success'  %>
  </div>
<% end %>

app/views/contributions/edit.html.erb
<h1>Editing Contribution</h1>

<%= render 'form' %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<h1>Listing Contributions</h1>

<%= paginate @contributions %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Job</th>      
      <th>Author</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contributions.each do |contribution| %>
      <tr>
        <td><%= contribution.job %></td>
        <td><%= link_to contribution.author.fullname, contribution.author %></td>
        <td><%= link_to contribution.book.title, contribution.book %></td>        
        <td><%= link_to t('show'), contribution %></td>
        <td><%= link_to t('edit'), edit_contribution_path(contribution) if policy(contribution).update? %></td>
        <td><%= link_to t('destroy'), contribution, method: :delete, data: { confirm: 'Are you sure?' } if policy(contribution).destroy? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contribution', new_contribution_path if policy(Contribution).new? %>

app/views/contributions/new.html.erb
<h1>New Contribution</h1>

<%= render 'form' %>

<%= link_to 'Back', contributions_path %>

app/views/contributions/show.html.erb
<p>
  <strong>Job:</strong>
  <%= @contribution.job %>
</p>

<p>
  <strong>Book:</strong>
  <%= @contribution.book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @contribution.author.fullname %>
</p>

<%= link_to 'Edit', edit_contribution_path(@contribution) if policy(@contribution).update? %> <br>
<%= link_to 'Back', contributions_path %>