config/routes.rb
Rails.application.routes.default_url_options[:host] = (Rails.env == 'production') ? 'bibliography.gr' : 'localhost:3000'
Rails.application.routes.draw do
  resources :shelves

  get '/autocomplete', to: 'home#autocomplete'

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :authors, :concerns => :paginatable do
    resources :awards, only: [:create, :edit, :update, :destroy]
    member do
      post 'favourite'
    end    
  end
  resources :awards, only: [:index], :concerns => :paginatable 

  resources :prizes, :contributions, :concerns => :paginatable

  resources :books, :concerns => :paginatable do
    member do
      get 'collections'
      post 'collections', to: 'books#manage_collections'
      post 'like'
      post 'dislike'
    end
    collection do
      get 'my'
    end
  end
  
  resources :publishers, :concerns => :paginatable do
    resources :places, only: [:create, :edit, :update, :destroy]
    collection do
      get 'search'
    end
  end 

  
  resource :profile, only: [:edit, :update]
  get "library/(:id)", :to => "profiles#show", as: 'public_profile'
  post "library/(:id)/follow", :to => "profiles#follow"

  
  
  get 'import', to: 'import#index', as: :import
  post 'import/url', to: 'import#import_from_url'
  post 'import/text', to: 'import#import_from_text'
  post 'import/file', to: 'import#import_from_file'

  get "import/storage", to: 'import#import_from_storage', as: :storage_import

  resources :categories do
    member do
      post 'favourite'
    end
  end

  devise_for :users

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
  

  namespace :api, defaults: {format: 'json'}  do
    namespace :v1 do
      resources :books, only: [:index, :show] do
        collection do
          get 'my'
        end
        resources :comments, except: [:new, :edit]
      end
      resources :authors, only: [:show] 
      resources :publishers, only: [:show]
      resources :categories, only: [:show]  
      resources :sessions, only: [:create]
      post 'authenticate', to: 'sessions#create'
    end
  end

  root to: 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend ActsAsTree::TreeWalker
  acts_as_tree order: "ddc"

  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]  

  has_and_belongs_to_many :books
  before_destroy { books.clear }

  validates :name, presence: true, :uniqueness => { scope: :ddc, message: 'This category already exists'}
  validates :ddc, presence: true    
  validates_with ParentValidator

  include PgSearch
  pg_search_scope :search_by_name, 
    :against => [
      [:name, 'A'],
      [:ddc, 'B'],
      [:tsearch_vector, 'C']
    ], 
    :using => {
      :tsearch => {:prefix => true, :tsvector_column => :tsearch_vector},
      :trigram => {:threshold => 0.15}
    }, 
    :ignoring => :accents

  after_validation :calculate_search_terms, :if => :recalculate_search_terms?

  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
      :slugged_name,
      [:slugged_name, :id],
    ]
  end  

  def slugged_name(opts={})
    opts[:max_expansions] ||= 1
    opts[:dashes] = true if opts[:dashes].nil?
    join_with = opts[:dashes] ? '-' : ' '

    converter = Greeklish.converter(max_expansions: opts[:max_expansions], generate_greek_variants: false)     
    name_to_slug = ApplicationController.helpers.detone(UnicodeUtils.downcase(name).gsub('ς','σ').gsub(/[,.:'·-]/,''))
    name_to_slug.split(" ").map do |word|
      converted = converter.convert(word)
      converted.present? ? converted : word
    end.flatten.uniq.join(join_with)
  end  

  def calculate_search_terms
    write_attribute(:tsearch_vector, slugged_name(max_expansions: 3, dashes: false) + ' ' + ddc)    
  end  

  def recalculate_search_terms?
    :name_changed? || :ddc_changed?
  end  
    
end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < Api::V1::BaseController
  def show
    category = Category.find(params[:id])    

    response = apply_format(Api::V1::CategorySerializer.new(category))
    
    render(json: response)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_json_format, only: [:favourite]
  before_action :authenticate_user!, only: [:favourite]
  before_action :set_category, only: [:show, :edit, :update, :destroy, :favourite]
  skip_after_action :verify_policy_scoped, only: :index

  #Disable protection for stateless api json response
  protect_from_forgery with: :exception, except: [:favourite]

  respond_to :html

  def index
    @categories = Category.roots

    # TODO Replace this with favourite or featured categories
    if params[:q].present?           
      keyphrase = ApplicationController.helpers.latinize(params[:q])
      @featured = Category.search_by_name(keyphrase).limit(100)   
    elsif user_signed_in?
      @featured = current_user.liked_categories.limit(10)
    else
      @featured = Category.where(featured: true).limit(10)
    end    

    if params[:autocomplete].try(:to_i) == 1 and params[:q].present?
      render json: @featured, each_serializer: Api::V1::Preview::CategorySerializer, root: false
    else
      respond_with(@categories)
    end       
  end

  def show
    @children = @category.children
    @books = @category.books.page(params[:page])

    respond_with(@category, @children)
  end

  def new
    @category = Category.new
    authorize @category    
    @category.parent_id = params[:parent_id]
    
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    authorize @category
    @category.save

    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  def favourite
    authorize :category, :favourite?

    if not current_user.likes?(@category)
      current_user.like(@category) 
    else
      current_user.unlike(@category)
    end

    render json: {status: 200, message: 'ok', favourite: current_user.likes?(@category)}
  end

  private
    def set_category
      @category = Category.find(params[:id])
      authorize @category
    end

    def category_params
      params.require(:category).permit(:name, :ddc, :slug, :biblionet_id, :parent_id, :featured)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<%= link_to category, class: "list-group-item", id: "category_#{category.id}" do %>
  <span class="badge"><%= "[#{category.ddc}]" %></span>
  <h5 class="list-group-item-heading">
    <%= "#{category.name}" %>  
  </h5> 
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category, class: 'form-bordered') do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t('name') %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :ddc %><br>
    <%= f.text_field :ddc, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :slug %><br>
    <%= f.text_field :slug, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :biblionet_id %><br>
    <%= f.number_field :biblionet_id, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :featured, class: 'control-label' %><br>
    <div>
      <%= label_tag(nil, class: 'csscheckbox csscheckbox-primary') do %>
        <%= f.check_box :featured %>
        <span></span>
      <% end %>      
    </div>
  </div>    

  <%= f.hidden_field :parent_id, value: @category.parent_id %><br>

  <div class="form-group form-actions">
    <%= f.submit t('save'), class: 'btn btn-effect-ripple btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="block">
  <div class="block-title">
    <h2><%= t('categories.editing') %></h2>
  </div>
  <%= render 'form' %>
</div>  

<%= link_to t('show'), @category %> |
<%= link_to t('back'), categories_path %>

app/views/categories/index.html.erb
<%= cell(:navigation).call(:content_header, content: render(partial: 'shared/search_form', 
    locals: {action: categories_path, placeholder: t('categories.search')}), breadcrumbs: {fa('home') => root_url, t('categories.label') => nil}) %>

<div class="row">  
  <div class="col-sm-8">
    <% @featured.each do |category|%>
      <%= render partial: 'books/widgets/grid', 
        locals: {title: link_to(category.name, category, class: "text-light-op"), books: category.books.limit(10)} %>
    <% end %>
  </div>
  

   <div class="col-sm-4">
      <div class="block">
        <div class="block-title">
          <div class="block-options pull-right">
            <%= cell(:navigation).call(:btn_link_to, name: fa('plus'), url: new_category_path, tooltip: t('categories.new')) if policy(Category).new? %>
          </div>
          <h2><%= t('categories.all') %></h2>
        </div>  
        <div class="list-group">
          <%= render @categories %>
        </div>              
      </div>
  </div>
</div>

app/views/categories/new.html.erb
<% pages = {fa('home') => root_url, t('categories.label') => categories_url, t('categories.new') => nil} %>

<%= cell(:navigation).call(:content_header, title: t('categories.new'), breadcrumbs: pages) %>

<%= render 'form' %>

<%= link_to t('back'), categories_path, class: "label label-default" %>

app/views/categories/show.html.erb
<% 
if @category.parent_id.nil? 
  pages = {fa('home') => root_url, t('categories.label') => categories_url, @category.name => nil}
else 
  pages = {fa('home') => root_url, t('categories.label') => categories_url, @category.parent.name => @category.parent, @category.name => nil}
end 
%>

<%= cell(:navigation).call(:content_header, content: render(partial: 'shared/search_form', 
    locals: {action: categories_path, placeholder: t('categories.search')}), breadcrumbs: pages) %>

<div class="row">
  <div class="col-sm-8">
      <div class="block full">
        <div class="block-title">
        <div class="block-options pull-right">  
          <% if current_user.likes?(@category) %>
          <%= button_tag fa('star'), :onclick => "javascript:favouriteCategory(#{@category.id})", class: "btn btn-effect-ripple btn-success btn-favourite-category-#{@category.id}", 
            data: { "toggle" => "tooltip", "original-title" => t('categories.favoured') }%>
          <% else %>
          <%= button_tag fa('star-o'), :onclick => "javascript:favouriteCategory(#{@category.id})", class: "btn btn-effect-ripple btn-primary btn-favourite-category-#{@category.id}", 
            data: { "toggle" => "tooltip", "original-title" => t('categories.add_to_favourites') }%>
          <% end %>
        </div>           
          <h2><%= detone @category.name %></h2>
        </div>

        <div class="row"> 
          <%= render "books/widgets/pagination" %>
          <hr> 
          <div class="col-xs-12">    
            <%= render :partial =>  "books/book", :collection => @books, :as => :book %>
          </div>
          <%= render "books/widgets/pagination" %>  
        </div>

      </div>
  </div>

  <div class="col-sm-4">
    <div class="block">
      <div class="block-title">
        <div class="block-options pull-right">
          <% if policy(@category).update? %>
          <%= cell(:navigation).call(:btn_link_to, name: fa('plus'), url: new_category_path(:parent_id => @category.id), tooltip: t('categories.new_subcategory')) %>
          <%= cell(:navigation).call(:btn_link_to, name: fa('pencil'), url: edit_category_path(@category), tooltip: t('categories.edit'), style: 'success') %>
          <% end %>  
          <%= link_to fa('times'), @category, class: "btn btn-effect-ripple btn-danger", 
            method: :delete, data: { confirm: t('u_sure'), "toggle" => "tooltip", "original-title" => t('categories.delete') } if policy(@category).destroy? %>
        </div>          
        <h2><%= detone t('categories.label') %></h2>
      </div>  
      <div class="list-group">
        <%= link_to "..", @category.parent_id.nil? ? categories_path : @category.parent, 
              class: 'list-group-item', id: "@category_#{@category.id}"  %>            
        <%= render @children %>
      </div>
    </div>
  </div>
</div>

<%= link_to t('back'), categories_path, class: "label label-default" %>