config/routes.rb
Rails.application.routes.default_url_options[:host] = (Rails.env == 'production') ? 'bibliography.gr' : 'localhost:3000'
Rails.application.routes.draw do
  resources :shelves

  get '/autocomplete', to: 'home#autocomplete'

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :authors, :concerns => :paginatable do
    resources :awards, only: [:create, :edit, :update, :destroy]
    member do
      post 'favourite'
    end    
  end
  resources :awards, only: [:index], :concerns => :paginatable 

  resources :prizes, :contributions, :concerns => :paginatable

  resources :books, :concerns => :paginatable do
    member do
      get 'collections'
      post 'collections', to: 'books#manage_collections'
      post 'like'
      post 'dislike'
    end
    collection do
      get 'my'
    end
  end
  
  resources :publishers, :concerns => :paginatable do
    resources :places, only: [:create, :edit, :update, :destroy]
    collection do
      get 'search'
    end
  end 

  
  resource :profile, only: [:edit, :update]
  get "library/(:id)", :to => "profiles#show", as: 'public_profile'
  post "library/(:id)/follow", :to => "profiles#follow"

  
  
  get 'import', to: 'import#index', as: :import
  post 'import/url', to: 'import#import_from_url'
  post 'import/text', to: 'import#import_from_text'
  post 'import/file', to: 'import#import_from_file'

  get "import/storage", to: 'import#import_from_storage', as: :storage_import

  resources :categories do
    member do
      post 'favourite'
    end
  end

  devise_for :users

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
  

  namespace :api, defaults: {format: 'json'}  do
    namespace :v1 do
      resources :books, only: [:index, :show] do
        collection do
          get 'my'
        end
        resources :comments, except: [:new, :edit]
      end
      resources :authors, only: [:show] 
      resources :publishers, only: [:show]
      resources :categories, only: [:show]  
      resources :sessions, only: [:create]
      post 'authenticate', to: 'sessions#create'
    end
  end

  root to: 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_after_action :verify_policy_scoped, only: :index
  skip_after_action :verify_authorized,  except: :index 

  def index    
    @search_results = Book.search(params[:query], page: params[:page], per_page: 25, fields: [:title, :description]) if params[:query].present?
    
    @popular_books = Book.order(impressions_count: :desc).limit(6)
    @latest_books = Book.order(created_at: :desc).where.not(image: '').limit(6)
    @recommended_books = Book.top(count: 6)    
     
    @awarded_books = Award.where(awardable_type: 'Book')
      .select('awards.awardable_id, awards.awardable_type, sum(awards.id) as awards_count')
      .group('awards.awardable_id, awards.awardable_type')
      .order('awards_count desc')
      .limit(6)
      .map {|award| award.awardable}


    @shelves = current_user.shelves if user_signed_in?
    @recently_added = current_user.bookshelves
      .select("bookshelves.book_id")
      .group('bookshelves.book_id')
      .order('max(bookshelves.created_at) desc')
      .limit(10)
      .map {|bookshelf| bookshelf.book} if user_signed_in?

  end

  def autocomplete
    autocomplete_results = Book.search(params[:query], autocomplete: true, limit: 10).map(&:title)    
    render json: autocomplete_results
  end  

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/widgets/_my_books.html.erb
<div class="widget">  
  <div class="widget-content widget-content-mini themed-background-dark-flat text-light-op border-bottom">
    <i class="fa fa-fw fa-book"></i> <strong><%= t('my_books') %></strong>
  </div>      
  <div class="widget-content">   
                   
     <div class="row">
        <div class="col-xs-12">
          <%= "#{current_user.books.distinct.count} #{t('books.label')} | #{@shelves.count} #{t('collections')} | #{current_user.writers.distinct.count} #{t('authors.label')}" %>
        </div>
        <div class="col-xs-12">
          <%= cell(:search).call(:search_form, url: '#', placeholder: t('search_my_books')) %>         
        </div>             
     </div>

  </div>
</div>

app/views/home/widgets/_my_collections.html.erb
<div class="widget">  
  <div class="widget-content widget-content-mini themed-background-dark-flat text-light-op border-bottom">
    <i class="fa fa-fw fa-th-large"></i> <strong><%= t('my_collections') %></strong>
  </div>      
  <div class="widget-content">
    <div class="row">
      <div class="col-xs-6 col-sm-4">
        <div class="row">
          <div class="col-xs-10">
            <%= link_to t('shelves.all_collections'), my_books_path %>  
          </div> 
          <div class="col-xs-2">
            <span class="pull-right"><%= current_user.books.distinct.count %></span>
          </div>
        </div>
      </div> 
      <% @shelves.each do |shelf| %>
        <div class="col-xs-6 col-sm-4">
          <div class="row">
            <div class="col-xs-10">
              <%= link_to shelf.screen_name, shelf %>  
            </div> 
            <div class="col-xs-2">
              <span class="pull-right"><%= shelf.books.count %></span>
            </div>
          </div>
        </div>
      <% end %>       
    </div>
  </div>
</div>

app/views/home/widgets/_welcome.html.erb
<div class="widget">  
  <div class="widget-content widget-content-mini themed-background-dark-flat text-light-op border-bottom">
    <span class="pull-right">(<%= t('some_options') %>)</span>
    <i class="fa fa-fw fa-home"></i> <strong><%= t('welcome') %></strong>
  </div>      
  <div class="widget-content">                
     <div class="row">
        <div class="col-xs-6 col-sm-4">
          <h4><%= t('add_books') %></h4>
          <%= link_to t('browse_books'), "#" %><br>
          <%= link_to t('add_books_to_library'), "#" %>
        </div> 
        <div class="col-xs-6 col-sm-4">
          <h4><%= t('spruce_up_profile') %></h4>
          <%= link_to t('edit_profile'), "#" %><br>
          <%= link_to t('add_member_photo'), "#" %>              
        </div> 
        <div class="col-xs-6 col-sm-4">
          <h4><%= t('engage') %></h4>
          <%= link_to t('read_reviews'), "#" %><br>
          <%= link_to t('invite_friends'), "#" %>              
        </div> 
     </div>

     <div class="push-bit-top">
        <a href="javascript:void(0)" class="btn btn-effect-ripple btn-xs btn-danger" style="overflow: hidden; position: relative;"><i class="fa fa-facebook"></i> Like</a>
        <a href="javascript:void(0)" class="btn btn-effect-ripple btn-xs btn-primary" style="overflow: hidden; position: relative;"><i class="fa fa-twitter"></i> Tweet</a>
     </div>
  </div>
</div>